# Generated by Django 4.1.7 on 2023-03-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=50)),
                ('nomesocial', models.CharField(max_length=50)),
                ('cns', models.CharField(max_length=15)),
            ],
        ),
    ]
